Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine319"
  config.vm.box_version = "4.3.12"

  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.hostname = "oaizabS"

  config.vm.synced_folder "./shared", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "oaizabS"
  end

  config.vm.provision "shell", path: "./scripts/master.sh"
end
