Vagrant.configure("2") do |config|
  config.vm.define "oaizab" do |master|
    master.vm.box = "generic/alpine319"
    master.vm.box_version = "4.3.12"

    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.hostname = "oaizabS"

    master.vm.synced_folder "./shared", "/vagrant", type: "virtualbox"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "Master"
    end

    master.vm.provision "shell", path: "./scripts/master.sh"
  end
  
  config.vm.define "oaizab1" do |node|
    node.vm.box = "generic/alpine319"
    node.vm.box_version = "4.3.12"

    node.vm.network "private_network", ip: "192.168.56.111"
    node.vm.hostname = "oaizabSW"

    node.vm.synced_folder "./shared", "/vagrant", type: "virtualbox"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
      vb.name = "Node"
    end

    node.vm.provision "shell", path: "./scripts/worker.sh"
  end
end
